CREATE DATABASE SAVEMONEY;

USE SAVEMONEY;

CREATE TABLE CADASTRO(
	ID_CADASTRO INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100),
    E_MAIL VARCHAR(50),
    SENHA  VARCHAR(100)
);

CREATE TABLE CARTEIRA(
		ID_CARTEIRA INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
		SALDO FLOAT(50)
        
);

CREATE TABLE POUPANCA(
	ID_POUPANCA INT(10) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    SALDO_POUP FLOAT(50)
);

